// Known-answer tests against vectors generated by the Go server.
//
// Testing the C++ implementation against itself would prove only that it is
// self-consistent, including consistently wrong. Every value here came from
// cmd/rudeauth-vectors running the server's real code paths.
#include "../src/crypto.hpp"

#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>

using namespace rudeauth::crypto;

namespace {

int g_failures = 0;
int g_checks   = 0;

void check(bool cond, const char* what) {
    ++g_checks;
    if (!cond) {
        ++g_failures;
        std::printf("  FAIL  %s\n", what);
    }
}

std::string g_vectors;

// A deliberately crude field reader. The real JSON parser arrives in a later
// task; this test must not depend on code it is meant to precede.
std::string field(const std::string& key) {
    const std::string needle = "\"" + key + "\"";
    const auto k = g_vectors.find(needle);
    if (k == std::string::npos) return {};
    const auto colon = g_vectors.find(':', k + needle.size());
    if (colon == std::string::npos) return {};
    const auto open = g_vectors.find('"', colon);
    if (open == std::string::npos) return {};
    const auto close = g_vectors.find('"', open + 1);
    if (close == std::string::npos) return {};
    return g_vectors.substr(open + 1, close - open - 1);
}

Bytes hexf(const std::string& key) {
    Bytes b;
    if (!hex_decode(field(key), b)) {
        std::printf("  FAIL  vector %s is not valid hex\n", key.c_str());
        ++g_failures;
    }
    return b;
}

} // namespace

int main(int argc, char** argv) {
    const char* path = argc > 1 ? argv[1] : "vectors.json";
    std::ifstream f(path, std::ios::binary);
    if (!f) {
        std::printf("cannot open %s\n", path);
        return 2;
    }
    std::ostringstream ss;
    ss << f.rdbuf();
    g_vectors = ss.str();

    std::printf("crypto known-answer tests\n");

    // ---------------------------------------------------------- SHA-256 ----
    {
        const Bytes in   = hexf("input_hex");
        const Bytes want = hexf("digest_hex");
        check(sha256(in) == want, "sha256 matches the server");
    }

    // ------------------------------------------------------ HMAC-SHA256 ----
    {
        const Bytes key  = hexf("key_hex");
        const Bytes data = hexf("data_hex");
        const Bytes want = hexf("digest_hex");
        // digest_hex appears twice; the first is SHA-256's. Locate the HMAC
        // block explicitly.
        const auto blk = g_vectors.find("\"hmac_sha256\"");
        const auto sub = g_vectors.substr(blk);
        const auto save = g_vectors;
        g_vectors = sub;
        const Bytes hkey = hexf("key_hex");
        const Bytes hdata = hexf("data_hex");
        const Bytes hwant = hexf("digest_hex");
        g_vectors = save;
        (void)key; (void)data; (void)want;
        check(hmac_sha256(hkey, hdata) == hwant, "hmac-sha256 matches the server");
    }

    // ------------------------------------------------------ HKDF-SHA256 ----
    {
        const auto blk = g_vectors.find("\"hkdf_sha256\"");
        const auto save = g_vectors;
        g_vectors = g_vectors.substr(blk);
        const Bytes secret = hexf("secret_hex");
        const Bytes salt   = hexf("salt_hex");
        const Bytes info   = hexf("info_hex");
        const Bytes want   = hexf("output_hex");
        g_vectors = save;
        check(hkdf_sha256(secret, salt, info, 32) == want, "hkdf-sha256 matches the server");
    }

    // ---------------------------------------------------------- Ed25519 ----
    //
    // THE critical test. Monocypher's default EdDSA is BLAKE2b based; linking
    // it instead of monocypher-ed25519 produces a library that rejects every
    // genuine signature. Catch that here, not in production.
    {
        const auto blk = g_vectors.find("\"ed25519\"");
        const auto save = g_vectors;
        g_vectors = g_vectors.substr(blk);
        const Bytes pub    = hexf("public_key_hex");
        const Bytes data   = hexf("data_hex");
        const Bytes signed_msg = hexf("signed_message_hex");
        const Bytes sig    = hexf("signature_hex");
        const std::string endpoint = field("endpoint");
        g_vectors = save;

        check(ed25519_verify(pub, signed_msg, sig), "ed25519 verifies the server's signature");

        // The full envelope path must reconstruct the same signed message.
        check(verify_envelope(pub, endpoint, data, sig),
              "verify_envelope reproduces the server's construction");

        Bytes tampered = data;
        tampered[0] = std::uint8_t(tampered[0] ^ 0x01);
        check(!verify_envelope(pub, endpoint, tampered, sig),
              "tampered payload is rejected");

        Bytes bad_sig = sig;
        bad_sig[0] = std::uint8_t(bad_sig[0] ^ 0x01);
        check(!verify_envelope(pub, endpoint, data, bad_sig),
              "corrupted signature is rejected");

        check(!verify_envelope(pub, "variables", data, sig),
              "a handshake signature does not verify as another endpoint");

        check(!verify_envelope(pub, "hand:shake", data, sig),
              "an ambiguous endpoint is rejected");
    }

    // ----------------------------------------------------------- X25519 ----
    {
        const auto blk = g_vectors.find("\"x25519\"");
        const auto save = g_vectors;
        g_vectors = g_vectors.substr(blk);
        const Bytes priv_a = hexf("private_a_hex");
        const Bytes pub_a  = hexf("public_a_hex");
        const Bytes priv_b = hexf("private_b_hex");
        const Bytes pub_b  = hexf("public_b_hex");
        const Bytes want   = hexf("shared_hex");
        g_vectors = save;

        Bytes derived_pub;
        check(x25519_public(priv_a, derived_pub) && derived_pub == pub_a,
              "x25519 public key matches the server");

        Bytes shared;
        check(x25519_shared(priv_a, pub_b, shared) && shared == want,
              "x25519 shared secret matches the server");

        Bytes other;
        check(x25519_shared(priv_b, pub_a, other) && other == want,
              "both directions agree");

        Bytes rejected;
        check(!x25519_shared(priv_a, Bytes(32, 0), rejected),
              "an all-zero peer key is rejected");
    }

    // ----------------------------------------------------- session key -----
    {
        const auto blk = g_vectors.find("\"session_key\"");
        const auto save = g_vectors;
        g_vectors = g_vectors.substr(blk);
        const std::string session_id = field("session_id");
        const Bytes want = hexf("key_hex");
        g_vectors = save;

        const auto xblk = g_vectors.find("\"x25519\"");
        const auto save2 = g_vectors;
        g_vectors = g_vectors.substr(xblk);
        const Bytes priv_a = hexf("private_a_hex");
        const Bytes pub_b  = hexf("public_b_hex");
        g_vectors = save2;

        Bytes key;
        check(derive_session_key(priv_a, pub_b, session_id, key) && key == want,
              "session key derivation matches the server end to end");
    }

    // ------------------------------------------ XChaCha20-Poly1305 ---------
    {
        const auto blk = g_vectors.find("\"xchacha20poly1305\"");
        const auto save = g_vectors;
        g_vectors = g_vectors.substr(blk);
        const Bytes key       = hexf("key_hex");
        const Bytes plaintext = hexf("plaintext_hex");
        const Bytes sealed    = hexf("sealed_hex");
        const std::string aad = field("aad");
        g_vectors = save;

        Bytes out;
        check(xchacha_open(key, sealed, aad, out) && out == plaintext,
              "xchacha20-poly1305 opens the server's sealed payload");

        Bytes wrong_aad_out;
        check(!xchacha_open(key, sealed, "files", wrong_aad_out),
              "a mismatched AAD is rejected");

        Bytes tampered = sealed;
        tampered[tampered.size() - 1] = std::uint8_t(tampered.back() ^ 0x01);
        Bytes tampered_out;
        check(!xchacha_open(key, tampered, aad, tampered_out),
              "tampered ciphertext is rejected");

        Bytes wrong_key(32, 0xAB);
        Bytes wrong_out;
        check(!xchacha_open(wrong_key, sealed, aad, wrong_out),
              "the wrong session key is rejected");
    }

    // --------------------------------------------------------- helpers -----
    {
        const Bytes data = {0x00, 0xFF, 0x10, 0x42, 0x7A};
        Bytes round;
        check(base64_decode(base64_encode(data), round) && round == data,
              "base64 round-trips");
        check(base64_encode(Bytes{'a'}) == "YQ==", "base64 pads correctly");

        Bytes hexr;
        check(hex_decode(hex_encode(data), hexr) && hexr == data, "hex round-trips");
        check(!hex_decode("abc", hexr), "odd-length hex is rejected");

        const Bytes r1 = random_bytes(32), r2 = random_bytes(32);
        check(r1.size() == 32 && r2.size() == 32 && r1 != r2,
              "random_bytes returns distinct values");
    }

    std::printf("%d checks, %d failures\n", g_checks, g_failures);
    return g_failures == 0 ? 0 : 1;
}
